[package]
name = "rust01"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libsql-client = "0.33.4"
sqlite = "0.33.0"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
